// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3eCxyOs2fh2o1Zmi6cppcDi8rEt32FZA',
    appId: '1:100035573401:web:9b3d181704ae7be9076a08',
    messagingSenderId: '100035573401',
    projectId: 'motivated-f7616',
    authDomain: 'motivated-f7616.firebaseapp.com',
    storageBucket: 'motivated-f7616.appspot.com',
    measurementId: 'G-79FLREJY2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhATaAm8GpXJ6bP-m3uM7JPQIPHO9EGBs',
    appId: '1:100035573401:android:e97a96fe216aa177076a08',
    messagingSenderId: '100035573401',
    projectId: 'motivated-f7616',
    storageBucket: 'motivated-f7616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJhoRe6NqfLXCrKHU3rpnKdm4It4Kh0Y',
    appId: '1:100035573401:ios:50b8b383456becca076a08',
    messagingSenderId: '100035573401',
    projectId: 'motivated-f7616',
    storageBucket: 'motivated-f7616.appspot.com',
    iosBundleId: 'com.example.motivato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTJhoRe6NqfLXCrKHU3rpnKdm4It4Kh0Y',
    appId: '1:100035573401:ios:50b8b383456becca076a08',
    messagingSenderId: '100035573401',
    projectId: 'motivated-f7616',
    storageBucket: 'motivated-f7616.appspot.com',
    iosBundleId: 'com.example.motivato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3eCxyOs2fh2o1Zmi6cppcDi8rEt32FZA',
    appId: '1:100035573401:web:e64c33b295247211076a08',
    messagingSenderId: '100035573401',
    projectId: 'motivated-f7616',
    authDomain: 'motivated-f7616.firebaseapp.com',
    storageBucket: 'motivated-f7616.appspot.com',
    measurementId: 'G-04QEC54YMH',
  );

}